## Build
name: Build
run-name: Build

on:
  release:
    types: [published]

jobs:
  canary-full-flow:
    uses: kaltura/ovp-pipelines-pub/.github/workflows/build_npm.yaml@master-VCP-14497
    with:
      build-command: 'build -- --prod'
      name: kmc-ng